apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-service
  namespace: store
  labels:
    project: online-store
    component: feedback-service
spec:
  replicas: 1
  selector:
    matchLabels:
      project: online-store
      component: feedback-service
  template:
    metadata:
      labels:
        project: online-store
        component: feedback-service
    spec:
      containers:
      - name: feedback-service
        image: devopsrinu/feedback-service:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8085
apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  namespace: store
  labels:
    project: online-store
    component: feedback-service
spec:
  selector:
    project: online-store
    component: feedback-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
